server:
  port: 0
  servlet:
    context-path: /mails

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

kafka.bootstrapAddress: localhost:9092